version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/conf/db.py
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://postgres:567234@db:5432/hw02